spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: 3dd545b7474b943d354c
            clientSecret: 2a2c4a395a5a6aaa69b0f21ebd611798c8a623c4
          google:
            client-id: 494924673041-cd6vd2jepkpoj3p53u0726rq6gqm32i3.apps.googleusercontent.com
            client-secret: _HkvP2MDNm-pEi44O5rFJJeo
# ...